### ISSUE TITLE
Make it available on the Chrome Web Store

### ISSUE THREAD

**Issue by waldyrious** [ricardobcl/HTML5-Speedy-Video-Extension#1]

**Comment by tag** [comment]
Add my voice for wanting this to appear in the Chrome store (and a precompiled Safari version too). I'd love to be able to point my university class at this, but they're not sophisticated enough to compile on their own.

**Comment by waldyrious** [comment]
I have been using youtube's native speed option for a while now. I believe it is only present in the html5 mode. Doesn't that cover the needs addressed by this extension?

**Comment by waldyrious** [comment]
Is this now viable with the [release of v2](https://github.com/ricardobcl/HTML5-Speedy-Video-Extension/releases/tag/v2.0)?

**Comment by ricardobcl** [comment]
It's now available on the [Chrome Web Store](https://chrome.google.com/webstore/detail/html5-speedy-video/caogcofklddclhfojcbmccggaohjngmh).

**Comment by waldyrious** [comment]
Yeah! Just tested it, works perfectly so far :D
