### ISSUE TITLE
A fix for Netflix's new React-based UI

### ISSUE THREAD

**Issue by foucist** [ricardobcl/HTML5-Speedy-Video-Extension#10]
Netflix seems to be rolling out a new React-based UI.

My hacky solution:

```
-var netflix_playerbar_name_class = ".player-status"; // name class of Netflix player bar
+var netflix_playerbar_name_class = ".ellipsize-text"; // name class of Netflix player bar

```
```
-        $("<span id=\"speedy_extension_addon_2_player\"></span>").appendTo(netflix_playerbar_name_class);
+        $("<span id=\"speedy_extension_addon_2_player\"></span>").prependTo(netflix_playerbar_name_class);
```

**Comment by foucist** [comment]
Another issue that I've noticed is when an episode is over, and netflix starts playing the next episode, the speedy addon doesn't show up, forcing a page reload.

**Comment by ricardobcl** [comment]
Thanks!! I haven't used Netflix in some time and missed this issue. You saved me some time with your comment.

There still are some bugs with continuous video watching (like the delta speed change going up with every new video, without a page reload). I'll probably should start separate issues for them.
