### ISSUE TITLE
Improve design of the ++/-- buttons

### ISSUE THREAD

**Issue by waldyrious** [ricardobcl/HTML5-Speedy-Video-Extension#7]
I didn't realize at first that they were buttons, and there are some spacing issues (for instance, the `--` button is glued to the video duration string).

I'll try working on this in a few days. For self reference, the relevant file to edit is [style.css](https://github.com/ricardobcl/HTML5-Speedy-Video-Extension/blob/master/src/style.css)

**Comment by ricardobcl** [comment]
Forgot to comment on this, but it now uses unicode characters for the buttons.
Changing them is also easy, just change the unicode decimal code.

**Comment by waldyrious** [comment]
I also forgot about this tbh.

> Changing them is also easy, just change the unicode decimal code.

Nice. I vote for these:
## `🐢 1.0x 🐇`

(j/k hehe)
