### ISSUE TITLE
Prebuilt Safari Extension

### ISSUE THREAD

**Issue by gustavobittencourt** [ricardobcl/HTML5-Speedy-Video-Extension#9]
Hello, Ricardo.

I don't have a Safari Developer Account. Could you provide a prebuilt version of the safari extension, if it's possible?

Thank you!

**Comment by ricardobcl** [comment]
Hi Gustavo, I would love to but I don't have a developer account myself (they cost 99$/year).
The alternative for Safari, and this is what I also do, is to install/build it with the extension builder in safari, every time you open safari. It takes 10 seconds max, and I don't close safari for several days, so it works for me. Of course, in chrome it's much simpler.

**Comment by gustavobittencourt** [comment]
I'm sorry, Ricardo! I just saw your answer today.

I'll try to take this approach.

Thank you very much.

Best regards,

Gustavo
